ci: iterate on aws integration test workflow
- eliminating setup-localstack action
- use services block to run separate localstack container
- separate container vs. runner OS params
- pass CI key secret through to workflow
- Faster build; skip javadoc
- Fix cloud_aws checkout action, tweak description
- Fix branch handling
- Add test excludes
- Try localstack kms
- Don't use path-style access for s3
- Sanity check local maven repo path
- Fix cache path issue: container vs host path
- Tweak support for virtual-hosted (non-path-style) access
- Try to skip waiting for localstack readiness
- Actions cache is immutable
- More s3a test excludes
- Consolodate common MAVEN_OPTS
- Address broken mvn verify return status..
- Update test-reporter action and filter artifact download
- Rename test exclude file, localstack-specific..
- Update aws integration test reporting workflow
- Consistent workflow name report_foo.yml
- Fix test report to avoid parsing failsafe summary
- Mind cancellations, tweak report workflow
- Use commit status to improve report usability
- Naming tweaks: concise and consistent
- Rename input to `toolchain_branch` for clarity
- Remove unnecessary `ports:` section for localstack service.
- Tweak s3a report name / context
- Add more S3A integration test excludes

diff --git a/.github/workflows/tmpl_cloud_aws.yml b/.github/workflows/tmpl_cloud_aws.yml
--- a/.github/workflows/tmpl_cloud_aws.yml
+++ b/.github/workflows/tmpl_cloud_aws.yml
@@ -15,8 +15,7 @@
 # limitations under the License.
 #
 
-name: AWS Integration
-
+name: s3a integration
 on:
   workflow_call:
     inputs:
@@ -24,18 +23,23 @@ on:
         required: false
         type: string
         default: 17
-      branch:
+      toolchain_branch:
         required: false
         type: string
-        description: Branch to run the build against
+        description: Branch to use for toolchain image build
         default: trunk
       os:
         required: false
         type: string
-        description: Operating system to run the build on
+        description: OS for container to run the build in
         default: ubuntu_24
+      runner_os:
+        required: false
+        type: string
+        description: OS tag for runner (e.g., Linux, ubuntu-24.04)
+        default: ubuntu_24.04
 
-# Security: Default to minimal permissions for workflow.
+# Security: Minimal defaults for workflow.
 permissions: {}
 
 concurrency:
@@ -44,7 +48,7 @@ concurrency:
     ${{ github.workflow }}
     ${{ github.repository == 'apache/hadoop' && github.run_id || github.ref }}
     ${{ inputs.java }}
-    ${{ inputs.branch }}
+    ${{ inputs.toolchain_branch }}
     ${{ inputs.os }}
   cancel-in-progress: true
 
@@ -53,22 +57,26 @@ env:
 
 jobs:
   precondition:
-    runs-on: ubuntu-24.04
+    runs-on: ${{ inputs.runner_os }}
     outputs:
       build_image_url: ${{ steps.img.outputs.build_image_url }}
     steps:
       - uses: actions/checkout@v6
+        with:
+          # Full fetch so build image URL can be computed for any branch
+          fetch-depth: 0
       - uses: ./.github/actions/build_image_url
         id: img
         with:
-          branch: ${{ inputs.branch }}
           os: ${{ inputs.os }}
+          branch: ${{ inputs.toolchain_branch }}
       - name: debug base_image_url
         run: |
           echo "precondition url: ${{ steps.img.outputs.build_image_url }}"
 
   build-image:
-    runs-on: ubuntu-24.04
+    name: Toolchain image (JDK${{ inputs.java }}, ${{ inputs.os }}-${{ inputs.toolchain_branch }})
+    runs-on: ${{ inputs.runner_os }}
     needs: [ precondition ]
     permissions:
       packages: write
@@ -82,44 +90,118 @@ jobs:
       - uses: ./.github/actions/build_image
         id: build_img
         with:
-          branch: ${{ inputs.branch }}
+          branch: ${{ inputs.toolchain_branch }}
           os: ${{ inputs.os }}
           build_image_url: ${{ needs.precondition.outputs.build_image_url }}
 
   test:
     name: S3A Integration Tests (Java ${{ inputs.java }})
     needs: [ precondition, build-image ]
-    runs-on: ubuntu-24.04
+    runs-on: ${{ inputs.runner_os }}
+    permissions:
+      # Security: Minimal permissions for the test runner. Reporting happens in
+      # report_cloud_aws.yml.
+      contents: read
+    services:
+      localstack:
+        image: localstack/localstack:latest
+        # Despite examples showing a `ports:` section, "You don't need to
+        # configure any ports for service containers. By default, all
+        # containers that are part of the same Docker network expose all ports
+        # to each other, and no ports are exposed outside of the Docker
+        # network." See:
+        # https://docs.github.com/en/actions/tutorials/use-containerized-services/use-docker-service-containers#running-jobs-in-a-container
+        env:
+          SERVICES: s3,kms
+          AWS_DEFAULT_REGION: us-west-2
+          AWS_ACCESS_KEY_ID: test
+          AWS_SECRET_ACCESS_KEY: test
+          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_CI_KEY }}
+          LOCALSTACK_HOST: s3.localstack
+
+        # Performance: Disable image's health check (localstack readiness): it typically takes less
+        # than a minute, and the Maven build that runs first takes longer than that.
+        # Also need to specify a dummy health-cmd or the github runner fails.
+        options: >-
+          --health-cmd "exit 0"
+          --health-interval 1s
+          --health-retries 1
+          --network-alias s3.localstack
+
     container:
       image: ${{ needs.precondition.outputs.build_image_url }}
-      options: --user ${{ needs.build-image.outputs.uid }}
+      options: >-
+        --user ${{ needs.build-image.outputs.uid }}
+    env:
+      # mvn verify doesn't return failure exit code due to HADOOP-18040
+      # (which seems incorrect, but let's just override this for now)
+      MAVEN_OPTS: >-
+        -Dmaven.test.failure.ignore=false
+        -Dmaven.repo.local=.m2/repository
+        -Dcheckstyle.skip -Dspotbugs.skip -Denforcer.skip -Drat.skip
     steps:
       - uses: actions/checkout@v6
+      # Performance: Caching TODO: We need to create a centralized maven build cache that is
+      # built on trunk. This will always miss on a new PR: Caches can't be
+      # shared between PR branches. PR branches *can* access caches from their
+      # base branch, though. See:
+      # https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching#restrictions-for-accessing-a-cache
+      # As-is, first run on a PR always misses. Subsequent cached builds see >100% speedup.
+      - name: Restore build cache
+        id: restore_cache
+        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
+        with:
+          path: |
+            .m2/repository/
+          key: ${{ inputs.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ inputs.toolchain_branch }}
+          # falls back to less-specific caches if exact key not found
+          restore-keys: |
+            ${{ inputs.os }}-maven-${{ hashFiles('**/pom.xml') }}-
+            ${{ inputs.os }}-maven-
       - name: Setup JDK ${{ inputs.java }}
         uses: actions/setup-java@v5
         with:
           distribution: zulu
           java-version: ${{ inputs.java }}
-          cache: 'maven'
-      - name: Localstack setup
-        # Security: 0.3.2 is an immutable tag, but ASF Infra policy still
-        # requires full SHA hashes.
-        uses: LocalStack/setup-localstack@7c8a0cb3405bc58be4c8f763f812aa000bc46303  # 0.3.2
-        with:
-          image-tag: 'latest'
-          install-awslocal: 'true'
-        env:
-          AWS_REGION: us-west-2
-          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_CI_KEY }}
-          AWS_ACCESS_KEY_ID: test
-          AWS_SECRET_ACCESS_KEY: test
 
       - name: Maven Build
         shell: bash
-        run: ./mvnw install -B -DskipTests -am -pl hadoop-tools/hadoop-aws
+        run: |
+          mkdir -p .m2/repository
+          ./mvnw -B -T 1C --no-transfer-progress -DskipTests -am -pl hadoop-tools/hadoop-aws \
+            -Dmaven.javadoc.skip -Dcheckstyle.skip -Dspotbugs.skip -Denforcer.skip -Drat.skip install
+
+      - name: Check local maven repository
+        shell: bash
+        run: |
+          if [ -d ".m2/repository" ]; then
+            echo "👍 Maven repository at $(pwd)/.m2/repository"
+          else
+            echo "👎 .m2/repository not found in $(pwd)"
+            exit 1
+          fi
+
+      - name: Save build cache
+        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
+        if: ${{ !cancelled() && steps.restore_cache.outputs.cache-hit != 'true' }}
+        with:
+          path: |
+            .m2/repository/
+          key: ${{ steps.restore_cache.outputs.cache-primary-key }}
+
       - name: Create localstack s3 bucket
         shell: bash
-        run: awslocal s3 mb s3://${{ env.BUCKET_NAME }}
+        run: |
+          # Use curl to interact with localstack if awslocal is not in the container
+          curl -X PUT "http://localstack:4566/${{ env.BUCKET_NAME }}"
+
+      - name: Register bucket hostname
+        shell: bash
+        run: |
+          # Resolve s3.localstack IP and add entry for virtual-hosted bucket FQDN
+          LSIP=$(getent hosts s3.localstack | awk '{print $1}')
+          echo "Registering ${{ env.BUCKET_NAME }}.s3.localstack as ${LSIP}"
+          echo "${LSIP} ${{ env.BUCKET_NAME }}.s3.localstack" | sudo tee -a /etc/hosts
 
       - name: S3A Integration Tests
         shell: bash
@@ -127,15 +209,22 @@ jobs:
           AWS_ACCESS_KEY_ID: test
           AWS_SECRET_ACCESS_KEY: test
           AWS_REGION: us-west-2
+          AWS_DEFAULT_REGION: us-west-2
         run: |
+          cp .github/workflows/templates/auth-keys.xml.tmpl \
+            hadoop-tools/hadoop-aws/src/test/resources/auth-keys.xml
           ./mvnw verify -B -pl hadoop-tools/hadoop-aws \
+            -Dparallel-tests \
             -DskipITs=false \
             -Dtest=none \
             -Dscale=true \
-            -Dfs.s3a.access.key=test \
-            -Dfs.s3a.secret.key=test \
-            -Dfs.s3a.endpoint=http://localhost:4566 \
-            -Dfs.s3a.connection.ssl.enabled=false \
-            -Dfs.s3a.path.style.access=true \
-            -Dfs.s3a.endpoint.region=us-west-2 \
-            -Dtest.fs.s3a.name=s3a://${{ env.BUCKET_NAME }}/
+            -Dfailsafe.excludesFile=$PWD/.github/gha-tests/hadoop-aws-localstack-excludes.txt
+
+      - name: Upload Test Reports
+        uses: actions/upload-artifact@v4
+        if: ${{ !cancelled() }}
+        with:
+          name: s3a-test-reports-java-${{ inputs.java }}-${{ inputs.os }}
+          path: |
+            **/target/failsafe-reports/*.xml
+            **/target/surefire-reports/*.xml
